# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 06:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=50)),
                ('name_last', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Your phone number must be in the '+999999999' format.", regex='^\\+?1?\\d{9,15}$')])),
                ('add_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
