# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name_first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name_last',
            new_name='last_name',
        ),
    ]
